# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

[en-ph]

[ja]
  title = "YOOkiã‚¯ãƒ­ãƒ‹ã‚¯ãƒ« ğŸ“œ"
  [ja.params]
    description = "Yahuhanan Yukia Sese Cunetaã®å¹´ä»£è¨˜ / áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®)."     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
    motto = "ã“ã‚ŒãŒå¿˜å´ã®çµ‚ã‚ã‚Šã§ã¯ãªã„ãªã‚‰ã€ç§ã¯è‡ªåˆ†ã®äººç”ŸãŒã¾ã•ã«ã“ã®æ—¥ã«çµ‚ã‚ã‚‹ã‹ã®ã‚ˆã†ã«æ¯æ—¥ç”Ÿãã‚‹ã§ã—ã‚‡ã†ã€‚"

[ko]
  title = "YOOki ì—°ëŒ€ê¸° ğŸ“œ"
  [ko.params]
    description = "Yahuhanan Yukia Sese Cunetaì˜ ì—°ëŒ€ê¸° / áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®)."      # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
    motto = "ì´ê²ƒì´ ë§ê°ì˜ ëì´ ì•„ë‹ˆë¼ë©´ ë‚´ ì¸ìƒì´ ë°”ë¡œ ì˜¤ëŠ˜ ëë‚  ë“¯ ë§¤ì¼ ì‚´ ê²ƒì´ë‹¤."
