### Info: https://gohugo.io/content-management/multilingual/#configure-languages

#[en]
  #languageName = "English"
  #languageFlag = "ğŸ‡¬ğŸ‡§"
  #languageCode = "en"
  #languageCodeCountry = "DO_NOT_USE"
  #timeZone = "Etc/UTC"
  #weight = 110

[en-ph]
  languageName = "English (PH)"
  languageFlag = "ğŸ‡µğŸ‡­"
  languageCodeCountry = "ph"
  timeZone = "Asia/Manila"
  weight = 111

#[fil]
  #languageName = "Filipino"
  #languageFlag = "ğŸ‡µğŸ‡­"
  #languageCode = "fil"
  #languageCodeCountry = "ph"
  #timeZone = "Asia/Manila"
  #weight = 120
  #title = ""
  #[fil.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[tl-tglg]
  #languageName = "Tagalog Baybayin"
  #languageFlag = "ğŸ‡µğŸ‡­"
  #languageCode = "tl-Tglg"
  #languageCodeCountry = "ph"
  #timeZone = "Asia/Manila"
  #weight = 121
  #title = ""
  #[tl.tglg.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hant]
  #languageName = "ä¸­æ–‡ï¼ˆç¹é«”ï¼‰"
  #languageFlag = "ğŸ‡¨ğŸ‡³"
  #languageCode = "zh-Hant"
  #languageCodeCountry = "cn"
  #timeZone = "Asia/Shanghai"
  #weight = 130
  #title = ""
  #[zh-hant.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hans]
  #languageName = "ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰"
  #languageFlag = "ğŸ‡¨ğŸ‡³"
  #languageCode = "zh-Hans"
  #languageCodeCountry = "cn"
  #timeZone = "Asia/Shanghai"
  #weight = 131
  #title = ""
  #[zh-hans.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ja]
  languageName = "æ—¥æœ¬èª"
  languageFlag = "ğŸ‡¯ğŸ‡µ"
  languageCode = "ja"
  languageCodeCountry = "jp"
  timeZone = "Asia/Tokyo"
  weight = 140
  title = "YOOkiã‚¯ãƒ­ãƒ‹ã‚¯ãƒ«"
  [ja.params]
    description = "Yahuhanan Yukia Sese Cunetaã®å¹´ä»£è¨˜ / áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®)."     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
    motto = "ã“ã‚ŒãŒå¿˜å´ã®çµ‚ã‚ã‚Šã§ã¯ãªã„ãªã‚‰ã€ç§ã¯è‡ªåˆ†ã®äººç”ŸãŒã¾ã•ã«ã“ã®æ—¥ã«çµ‚ã‚ã‚‹ã‹ã®ã‚ˆã†ã«æ¯æ—¥ç”Ÿãã‚‹ã§ã—ã‚‡ã†ã€‚"

[ko]
  languageName = "í•œêµ­ì–´"
  languageFlag = "ğŸ‡°ğŸ‡·"
  languageCode = "ko"
  languageCodeCountry = "kr"
  timeZone = "Asia/Seoul"
  weight = 150
  title = "YOOki ì—°ëŒ€ê¸°"
  [ko.params]
    description = "Yahuhanan Yukia Sese Cunetaì˜ ì—°ëŒ€ê¸° / áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®)."      # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
    motto = "ì´ê²ƒì´ ë§ê°ì˜ ëì´ ì•„ë‹ˆë¼ë©´ ë‚´ ì¸ìƒì´ ë°”ë¡œ ì˜¤ëŠ˜ ëë‚  ë“¯ ë§¤ì¼ ì‚´ ê²ƒì´ë‹¤."
